### ISSUE TITLE
Extension throws non-Error instance on connection error

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph-go#59]
When a WebSocket connection fails, the browser console gets a plain `Error` log with no stack trace or indication what (and which extension) failed:

![image](https://user-images.githubusercontent.com/10532611/55278810-7ab8ed80-5311-11e9-86bc-c99aa96c03d0.png)

This is because the extension throws an `Event` instance here instead of with a `Error` instance (with a message and a stack trace):

https://github.com/sourcegraph/sourcegraph-go/blob/cbdae137c0eebca495dd64d7dd4ebd2f1c853524/src/lang-go.ts#L206

This can easily happen in local dev if the Go langserver is not running and results in wasted time because it is unknown where the error comes from.

**Comment by chrismwendt** [comment]
Do you see `lang-to.ts` on the right?

![image](https://user-images.githubusercontent.com/1387653/55297368-334a6400-53da-11e9-85b8-3cff263d6678.png)

That links to the source code of `lang-go.ts`

![image](https://user-images.githubusercontent.com/1387653/55297380-4eb56f00-53da-11e9-9f45-0a75fe14f70c.png)

When I

```typescript
        webSocket.addEventListener('error', event => reject(new Error('test')))
```

The stack trace pretty much looks the same:

![image](https://user-images.githubusercontent.com/1387653/55297413-a81d9e00-53da-11e9-97c2-2f6e1a194a83.png)

Is comlink responsible for propagating the stack trace?

**Comment by felixfbecker** [comment]
> Do you see lang-to.ts on the right?

Look at the error below that, it does not point to lang-go.ts

> The stack trace pretty much looks the same:

That error has a proper stack trace pointing to `at WebSocket.<anonymous> (lang-go.js:63687`, which is a big difference

> Is comlink responsible for propagating the stack trace?

Yep
