### ISSUE TITLE
editor: where is the repo for the live editor?

### ISSUE THREAD

**Issue by mbana** [sourcegraph/sourcegraph-go#6]
Hi,

I am trying to find the reference to the repo that contains the code to setup Monaco.
Is this available somewhere? I've tried all sorts of search queries: `readOnly` option, as per https://microsoft.github.io/monaco-editor/playground.html#creating-the-editor-editor-basic-options, to see if I can somehow toggle the `readOnly` mode to false.

Thanks,

**Comment by sqs** [comment]
Hi @mbana. Are you referring to the code viewer UI on Sourcegraph.com? This repo is just the language server and vscode extension, not the full Sourcegraph.com repo.

**Comment by mbana** [comment]
Oh ok, yes was I sort of thought as well.
Do you plan on opening sourcing the part that embed Monaco Editor?
If that's asking for too much, would you care to even share how you go about embedding the editor. I've got a rough idea on how you'd do this; I suspect you have custom version of the `monaco-editor` linked to the UI?

**Comment by sqs** [comment]
The part that embeds the Monaco editor is all glue that wouldn't be super helpful outside of Sourcegraph. It's glue between Sourcegraph and the open-source github.com/Microsoft/vscode repo. We are going to submit some PRs upstream to the vscode repo to make integration easier for other folks in the next few weeks most likely.
